services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nakama
      POSTGRES_PASSWORD: localdb
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --name nakama1 --database.address postgres:localdb@postgres:5432/nakama --logger.level DEBUG
    ports:
      - "7350:7350"
      - "7351:7351"
    volumes:
      - ./src/modules:/nakama/data/modules

  node-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - nakama
    environment:
      - PORT=5000
      - NAKAMA_HOST=nakama
      - NAKAMA_PORT=7350
      - NAKAMA_SERVER_KEY=defaultkey

volumes:
  data:
